# Generated by Django 5.2.4 on 2025-08-04 02:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_cata", "0003_alter_cata_intensidad_acidez_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cata",
            name="dulzura",
            field=models.IntegerField(
                default=0,
                help_text="Número de checkboxes marcados (0-5)",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="cata",
            name="taza_limpia",
            field=models.IntegerField(
                default=0,
                help_text="Número de checkboxes marcados (0-5)",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="cata",
            name="tazas",
            field=models.IntegerField(
                default=5,
                help_text="Número de tazas (1-10)",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(10),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="cata",
            name="uniformidad",
            field=models.IntegerField(
                default=0,
                help_text="Número de checkboxes marcados (0-5)",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
    ]
