# Generated by Django 5.2.4 on 2025-08-03 20:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_cata", "0001_add_tueste_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cata",
            name="intensidad_acidez",
            field=models.IntegerField(
                help_text="Intensidad de 0 a 5",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="cata",
            name="intensidad_aroma",
            field=models.IntegerField(
                help_text="Intensidad de 0 a 5",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="cata",
            name="intensidad_cuerpo",
            field=models.IntegerField(
                help_text="Intensidad de 0 a 5",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="cata",
            name="intensidad_fragancia",
            field=models.IntegerField(
                help_text="Intensidad de 0 a 5",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="cata",
            name="tazas",
            field=models.IntegerField(
                default=1,
                help_text="Número de tazas (1-10)",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(10),
                ],
            ),
        ),
    ]
