# Generated by Django 5.2.4 on 2025-08-03 20:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_cata", "0002_alter_cata_intensidad_acidez_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cata",
            name="intensidad_acidez",
            field=models.IntegerField(
                help_text="Intensidad de 0 a 10",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(10),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="cata",
            name="intensidad_aroma",
            field=models.IntegerField(
                help_text="Intensidad de 0 a 10",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(10),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="cata",
            name="intensidad_cuerpo",
            field=models.IntegerField(
                help_text="Intensidad de 0 a 10",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="cata",
            name="intensidad_fragancia",
            field=models.IntegerField(
                help_text="Intensidad de 0 a 10",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(10),
                ],
            ),
        ),
    ]
