# Generated by Django 4.2.7 on 2025-08-04 07:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_cata", "0004_alter_cata_dulzura_alter_cata_taza_limpia_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cata",
            name="intensidad_cuerpo",
            field=models.IntegerField(
                help_text="Intensidad de 0 a 10",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(10),
                ],
            ),
        ),
    ]
